# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee796a57bc907022185700228c911040dd2439a4e56f31893deba858e3c24f0ab15855d81cc5e754abbc6d512a8f880623813094bca9def49f24108947d9aa27

test:
  secret_key_base: 22ab2ddcb05d337e1916636065628e4a3f806ffc4010db4896c683b4f1096dec3826bc549e3d37970c34077f7dea4d2138434af773bceb276c443a2ce6b776d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
